# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qiangdan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qiangdan
pod 'AFNetworking'
pod "SVProgressHUD-0.8.1"
pod 'SDWebImage'
pod "MJRefresh"
pod 'Masonry'

pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SDCycleScrollView', '~> 1.80'
pod 'TYPagerController'
pod 'MJExtension'


pod 'MBProgressHUD', '~> 1.1.0'


pod 'UMCCommon'
#pod 'UMCSecurityPlugins'
pod 'UMCCommonLog'
pod 'UMCPush'

end
